import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowUpRight,ArrowRight,Check,CheckCheck,ChevronDown,ChevronRight,Clock3,Copy,FileText,Headphones,Leaf,LoaderCircle,LockKeyhole,Package,Pause,ShieldCheck,ThumbsUp,X,RotateCcw,CircleCheck,AlertCircle} from 'lucide-react';
import {api,saved,saveSession,uuid,chatStream,track,flushEvents,ApiError,consumerError,SERVICE_MESSAGE} from './api';
import {PUBLIC_HELP} from './publicHelp';
import './reliability.css';
import type {Conversation,Order,Goal,Message,Card,HelpInfo,Source,Preview} from './types';
import {Avatar,Seen,Modal,OrderMini,ApplicationFields,PreviewCard,FeedbackForm} from './components';
import {MessageText} from './MessageText';
import {EvidenceContent, ServiceSummary} from './DocumentContent';
const labels:Record<string,string>={qa:'咨询规则',query:'查询订单',eligibility:'判断申请资格',application:'申请售后'};
const states:Record<string,string>={awaiting_goal:'待明确事项',awaiting_object:'待选择订单',awaiting_fields:'待补充信息',awaiting_confirmation:'待你确认',processing:'处理中',completed:'当前目标已完成',unknown:'提交结果待核实',needs_help:'需要进一步确认',cancelled:'未提交已取消',rejected:'明确未创建',unsupported:'超出本期范围',existing_application:'已有申请'};
export default function App(){
 const [state,setState]=useState<Conversation|null>(null),[boot,setBoot]=useState(true),[busy,setBusy]=useState(false),[mutation,setMutation]=useState(false),[input,setInput]=useState(''),[error,setError]=useState('');
 const [orders,setOrders]=useState<Order[]>([]),[showOrders,setShowOrders]=useState(false),[ordersLoading,setOrdersLoading]=useState(false),[ordersError,setOrdersError]=useState(''),[help,setHelp]=useState<HelpInfo|null>(null),[source,setSource]=useState<Source|null>(null),[feedback,setFeedback]=useState<Message|null>(null),[identity,setIdentity]=useState(false),[pendingText,setPendingText]=useState(''),[uncertain,setUncertain]=useState(false);
 const [profiles,setProfiles]=useState<Array<'lin'|'chen'>>([]),[profilesLoading,setProfilesLoading]=useState(true),[profilesError,setProfilesError]=useState(false);
 const loadProfiles=async()=>{setProfilesLoading(true);setProfilesError(false);try{const result=await api<{profiles:Array<'lin'|'chen'>}>('/demo-profiles');setProfiles(result.profiles)}catch(e){setProfiles([]);setProfilesError(true);fail(e)}finally{setProfilesLoading(false)}};
 useEffect(()=>{void loadProfiles()},[]);
 const bottom=useRef<HTMLDivElement>(null),composer=useRef<HTMLTextAreaElement>(null),root=state?'/conversations/'+state.id:'',paused=state?.automation_state==='paused';
 const [helpBlocked,setHelpBlocked]=useState(false),[helpLoading,setHelpLoading]=useState(false);
 const helpRequest=useRef(false);
 const blocked=paused||helpBlocked;
 const fail=(e:unknown)=>{setError(consumerError(e));if(e instanceof ApiError&&e.code==='unauthenticated'){setState(null);setIdentity(true)}};
 const refresh=async()=>{const s=saved();if(s){const v=await api<Conversation>('/conversations/'+s.cid);setState(v);if(v.action||v.preview?.invalidated)setUncertain(false)}};
 useEffect(()=>{const s=saved();if(!s){setBoot(false);return}api<Conversation>('/conversations/'+s.cid+'?resume=true').then(setState).catch(fail).finally(()=>setBoot(false));void flushEvents()},[]);
 useEffect(()=>{if(!error||!state)return;const frame=requestAnimationFrame(()=>{const el=document.querySelector('[role="alert"]');if(!el||document.visibilityState!=='visible'||el.getBoundingClientRect().bottom<=0)return;try{const timing=JSON.parse(sessionStorage.getItem('yx.timing.'+state.id)||'null');if(timing&&!timing.done&&timing.timeOrigin===performance.timeOrigin){track(state.id,'answer_presented',{task_id:state.task?.id,interaction_id:timing.iid,duration_ms:performance.now()-timing.start,answer_type:'explicit_exit'});timing.done=true;sessionStorage.setItem('yx.timing.'+state.id,JSON.stringify(timing))}}catch{}});return()=>cancelAnimationFrame(frame)},[error,state?.id]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'})},[state?.messages.length,busy]);
 useEffect(()=>{if(!state||(!state.inflight&&state.action?.status!=='unknown'&&!uncertain))return;const timer=setInterval(()=>void refresh().catch(()=>{}),4000);return()=>clearInterval(timer)},[state?.inflight,state?.action?.status,uncertain,state?.id]);
 useEffect(()=>{const online=()=>{void refresh().catch(fail);void flushEvents()};window.addEventListener('online',online);return()=>window.removeEventListener('online',online)},[]);
 useEffect(()=>{if(!state||(!help&&(!showOrders||ordersLoading||ordersError)))return;let sent=false;const report=()=>{const el=document.querySelector('[role="dialog"]');if(sent||!el||document.visibilityState!=='visible')return;const box=el.getBoundingClientRect();if(box.top<innerHeight&&box.bottom>0){sent=true;track(state.id,help?'help_entry_presented':'object_selection_shown',{task_id:state.task?.id,...(help?{availability:help.availability}:{candidate_count:orders.length})})}};const frame=requestAnimationFrame(report);document.addEventListener('visibilitychange',report);return()=>{cancelAnimationFrame(frame);document.removeEventListener('visibilitychange',report)}},[help,showOrders,ordersLoading,ordersError,orders.length,state?.id]);
 async function login(profile:'lin'|'chen'){if(!profiles.includes(profile))return;setBusy(true);setError('');try{localStorage.removeItem('yx.events');const s=await api<{csrf:string;conversation_id:string}>('/demo-session',{profile});saveSession({csrf:s.csrf,cid:s.conversation_id});setState(await api<Conversation>('/conversations/'+s.conversation_id));setIdentity(false);setInput('')}catch(e){fail(e)}finally{setBusy(false)}}
 async function send(text=input,goal?:Goal){if(!state||!text.trim()||busy||blocked)return;setBusy(true);setError('');setPendingText(text);setInput('');const iid=uuid(),start=performance.now();sessionStorage.setItem('yx.timing.'+state.id,JSON.stringify({iid,start,timeOrigin:performance.timeOrigin,existing:state.messages.map(m=>m.id),done:false}));track(state.id,'user_interaction_recorded',{interaction_id:iid,task_id:state.task?.id,client_monotonic_ms:start,action_result:'send'});
 try{await chatStream(state.id,text,iid,goal,v=>{setState(v);track(v.id,'user_interaction_recorded',{interaction_id:iid,task_id:v.task?.id,duration_ms:performance.now()-start,action_result:'response_received'})})}catch(e){fail(e);setInput(text);await refresh().catch(()=>{})}finally{setBusy(false);setPendingText('');composer.current?.focus()}}
 async function mutate(path:string,body:unknown){if(mutation)return;const data=body as Record<string,unknown>,iid=(data.confirmation_id||data.interaction_id||uuid()) as string,start=performance.now();if(state){track(state.id,'user_interaction_recorded',{task_id:state.task?.id,interaction_id:iid,interaction_type:path.includes('confirm')?'confirm':path.slice(1),client_monotonic_ms:start});if(path==='/preview'||path.includes('/confirm'))sessionStorage.setItem('yx.timing.'+state.id,JSON.stringify({iid,start,timeOrigin:performance.timeOrigin,existing:state.messages.map(m=>m.id),done:false}))}setMutation(true);setError('');try{setState(await api<Conversation>(root+path,{...data,interaction_id:iid}))}catch(e){fail(e);throw e}finally{setMutation(false)}}
 async function openOrders(){setShowOrders(true);setOrdersLoading(true);setOrdersError('');setOrders([]);setError('');try{const d=await api<{orders:Order[]}>('/orders');setOrders(d.orders)}catch(e){setOrdersError(SERVICE_MESSAGE);fail(e)}finally{setOrdersLoading(false)}}
 async function bind(o:Order){if(!state)return;const iid=uuid();track(state.id,'object_selected',{task_id:state.task?.id,interaction_id:iid,object_ref:o.id});try{const goal=state.task?.active && !state.order && state.task.goal in labels?state.task.goal as Goal:undefined;await mutate('/binding',{order_id:o.id,interaction_id:iid});setShowOrders(false);if(goal)await send(labels[goal],goal)}catch{}}
 async function openHelp(){
  setHelp({...PUBLIC_HELP,pause_confirmed:paused});setHelpBlocked(true);setIdentity(false);
  if(!state||mutation||helpRequest.current)return;
  helpRequest.current=true;setHelpLoading(true);
  try{
   const next=await api<Conversation>(root+'/control',{mode:'paused',interaction_id:uuid()});setState(next);
   setHelp(h=>h?{...h,pause_confirmed:next.automation_state==='paused'}:h);
   const details=await api<HelpInfo>(root+'/help');setHelp(h=>h?details:h);
  }catch(e){fail(e)}finally{helpRequest.current=false;setHelpLoading(false)}
 }
 async function resume(){if(helpRequest.current)return;if(!state){setHelpBlocked(false);setHelp(null);return}try{await mutate('/control',{mode:'active',interaction_id:uuid()});setHelpBlocked(false);setHelp(null)}catch{}}
 async function readSource(id:string){try{setSource(await api<Source>(root+'/sources/'+encodeURIComponent(id)))}catch(e){fail(e)}}
 async function confirm(p:Preview){if(!state||uncertain)return;const iid=uuid();track(state.id,'confirmation_clicked',{task_id:state.task?.id,preview_id:p.id,interaction_id:iid,confirmation_id:iid});setUncertain(true);try{await mutate('/previews/'+p.id+'/confirm',{content_hash:p.content_hash,confirmation_id:iid});setUncertain(false)}catch{await refresh().catch(()=>{})}}
 async function queryAction(id:string){setMutation(true);try{setState(await api<Conversation>(root+'/actions/'+id));setUncertain(false)}catch(e){fail(e)}finally{setMutation(false)}}
 function fieldCommit(field:string){if(state)track(state.id,'user_interaction_recorded',{task_id:state.task?.id,interaction_id:uuid(),interaction_type:'field_'+field})}
 function sources(ids?:string[]){return ids?.length?<div className="sources">{ids.map(id=><button key={id} onClick={()=>void readSource(id)}><FileText size={13}/>{id.endsWith('policy')?'退货申请规则':id.endsWith('product')?'商品说明':'物流说明'}<ArrowUpRight size={12}/></button>)}</div>:null}
 function card(c:Card,m:Message){
  if(c.type==='order_picker')return <button className="card-action" onClick={()=>void openOrders()}><Package size={18}/>选择我的订单<ArrowRight size={17}/></button>;
  if(c.type==='goal_choice')return <div className="goal-options">{c.goals?.map(g=><button key={g} disabled={busy||paused||!(g in labels)} onClick={()=>void send(labels[g],g)}>{labels[g]||g}<ChevronRight size={14}/></button>)}</div>;
  if(c.type==='sources'||c.type==='eligibility')return <>{c.type==='eligibility'&&<div className={'eligibility '+(c.allowed?'positive':'neutral')}>{c.allowed?<ShieldCheck size={16}/>:<AlertCircle size={16}/>}<span>{c.allowed?'时限与订单状态符合，可继续核对申请条件':'当前不符合演示申请条件'}</span></div>}{sources(c.source_ids)}</>;
  if(c.type==='application_fields')return <ApplicationFields onFieldCommit={fieldCommit} key={m.id} initial={state?.task?.fields||c.fields||{}} disabled={mutation||blocked||state?.task?.id!==m.task_id||!state.task.active} onSubmit={async data=>{await mutate('/preview',data)}} sources={sources(c.source_ids)}/>;
  if(c.type==='preview'){const p=state?.preview;return p && p.id===c.preview_id?<Seen cid={state!.id} message={m} event="application_preview_presented" extra={{preview_id:p.id,preview_valid:!p.invalidated&&new Date(p.expires_at).getTime()>Date.now()}}><PreviewCard preview={p} disabled={mutation||blocked||uncertain} onConfirm={()=>void confirm(p)} onCancel={()=>void mutate('/cancel',{}).catch(()=>{})}/><details className="edit-fields"><summary>修改申请内容</summary><ApplicationFields onFieldCommit={fieldCommit} initial={state?.task?.fields||{}} disabled={mutation||blocked||p.invalidated} onSubmit={async data=>{await mutate('/preview',data)}}/></details></Seen>:<div className="old-state"><Clock3 size={15}/>历史预览已失效，请以当前事项为准。</div>}
  if(c.type==='result'){const a=state?.actions?.[c.action_id!]||(state?.action?.id===c.action_id?state?.action:null);return <div className={'business-card '+(a?.status==='unknown'?'unknown':'')}><div className="card-title">{a?.status==='accepted'?<CircleCheck size={20}/>:<Clock3 size={20}/>}<strong>{a?.status==='accepted'?'申请已受理':a?.status==='not_created'?'申请明确未创建':'提交结果待核实'}</strong></div>{a?.application_id&&<><span className="field-label">申请编号</span><code className="application-id">{a.application_id}</code></>}<p className="micro">{a?.status==='accepted'?'等待业务处理。受理不等于审核通过或退款到账。':'请查询原动作，不要重复创建申请。'}</p><button className="soft-button" disabled={mutation} onClick={()=>void queryAction(c.action_id!)}><RotateCcw size={14}/>查询原申请</button></div>}
  if(c.type==='existing_application')return <div className="business-card"><strong>已有受理中的申请</strong><code className="application-id">{c.id}</code><p className="micro">请查询原申请；不重复提交。</p></div>;
  if(c.type==='order_result'&&c.order)return <div className="business-card"><OrderMini order={c.order}/><div className="timeline">{c.order.logistics.map((l,i)=><div key={i}><span className="timeline-dot"/><strong>{l.text}</strong><small>{l.time}</small></div>)}</div>{c.applications?.map(a=><p key={a.id} className="micro">售后申请：{a.id} · 已受理待处理</p>)}<div className="card-foot"><CheckCheck size={13}/>来自合成业务记录 · {new Date(c.order.updated_at).toLocaleString('zh-CN')}</div></div>;
  if(c.type==='help'||c.type==='help_offer')return <button className="text-button" onClick={()=>void openHelp()}><Headphones size={15}/>查看帮助入口<ArrowUpRight size={13}/></button>;
  return null
 }
 if(boot)return <div className="boot"><Avatar large/><LoaderCircle className="spin"/><p>正在恢复你的服务进度</p><button onClick={()=>{setBoot(false);void openHelp()}}>联系客服</button></div>;
 return <div className="app-shell">
  <header className="topbar"><div className="brand"><div className="brand-avatar"><Avatar/></div><div><div className="brand-name">YxWoof<span>AI 客服</span></div><p>每件小事，认真回应</p></div></div><div className="header-right"><span className="demo-pill"><span/>合成演示环境</span>{state&&<button className="profile-button" aria-label="切换演示账号" onClick={()=>setIdentity(true)}><span className="profile-initial">{state.consumer.name.slice(-1)}</span>{state.consumer.name}<ChevronDown size={13}/></button>}</div></header>
  <div className="workspace"><main className="chat-panel">
   <div className="chat-panel-head"><div><span className={'presence '+(paused?'is-paused':'')}/><strong>{paused?'AI 已暂停':'你的专属购物小帮手'}</strong><span className="desktop-label">有据回答 · 确认后办理</span></div><button className="text-button help-top" onClick={()=>void openHelp()}><Headphones size={16}/>寻求帮助</button></div>
   <div className="chat-scroll">{(!state||state.messages.length<=1)&&<section className="welcome"><div className="welcome-mascot"><span className="spark spark-one">✦</span><Avatar large/><span className="spark spark-two">✧</span><span className="mascot-badge"><Check size={13}/></span></div><span className="eyebrow">HELLO, I'M YXWOOF</span><h1>你好，有什么我可以帮你？</h1><p>从一句话开始，把购物中的小困扰交给我。<br/>每一步有依据，每次办理由你确认。</p><div className="welcome-badges"><span><ShieldCheck size={14}/>只看你的订单</span><span><FileText size={14}/>回答附带依据</span><span><LockKeyhole size={14}/>办理先经确认</span></div>
   {!state?<div className="profile-selection"><span className="field-label">{profilesLoading?'正在检查演示配置':profilesError?SERVICE_MESSAGE:profiles.length?'选择一个合成账号，开始体验':'尚未配置演示业务数据'}</span>{!profilesLoading&&<button className="text-button" onClick={()=>void loadProfiles()}>重新检查配置</button>}<div><button disabled={busy||profilesLoading||!profiles.includes('lin')} onClick={()=>void login('lin')}><span className="profile-initial">林</span><strong>我是小林</strong><ArrowRight size={17}/></button><button disabled={busy||profilesLoading||!profiles.includes('chen')} onClick={()=>void login('chen')}><span className="profile-initial peach">陈</span><strong>我是小陈</strong><ArrowRight size={17}/></button></div><small>两个账号的数据相互隔离，均不涉及真实交易。</small></div>:<div className="quick-actions">{([{goal:'query',icon:Package,title:'我的订单到哪了',sub:'订单状态、物流进度'},{goal:'qa',icon:FileText,title:'想了解商品和规则',sub:'找到适用于本店的依据'},{goal:'application',icon:RotateCcw,title:'帮我准备售后申请',sub:'先核对，再由你确认'}] as const).map(q=><button key={q.goal} disabled={busy||blocked} onClick={()=>void send(labels[q.goal],q.goal)}><span className={'quick-icon '+q.goal}><q.icon size={21}/></span><strong>{q.title}</strong><span>{q.sub}</span><ArrowUpRight className="quick-arrow" size={16}/></button>)}</div>}</section>}
   {state&&state.messages.filter(m=>!m.cards.some(c=>c.type==='welcome')).map(m=><div key={m.id} className={'message-row '+m.role}>{m.role==='assistant'&&<Avatar/>}<div className="message-stack">{m.role==='assistant'&&<div className="message-label">YxWoof <span>AI</span></div>}<Seen cid={state.id} message={m} taskStartedAt={state.task?.id===m.task_id?state.task.created_at:undefined} event={m.role==='assistant'?'answer_presented':'user_interaction_recorded'}><div className="bubble"><MessageText text={m.text} role={m.role}/>{m.cards.map((c,i)=><div key={i}>{card(c,m)}</div>)}</div></Seen>{m.role==='assistant'&&m.task_id&&<div className="message-tools"><Seen cid={state.id} message={m} event="feedback_invited"><button aria-label="反馈这条回复" onClick={()=>setFeedback(m)}><ThumbsUp size={13}/><span>反馈</span></button></Seen><span>{new Date(m.created_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</span></div>}</div></div>)}
   {busy&&pendingText&&<><div className="message-row user"><div className="bubble pending">{pendingText}</div></div><div className="message-row assistant"><Avatar/><div className="thinking"><span/><span/><span/><small>正在理解并处理你的诉求</small></div></div></>}<div ref={bottom}/></div>
   <div className="composer-area">{error&&<div className="error-banner" role="alert"><AlertCircle size={16}/><span>{error}</span>{error===SERVICE_MESSAGE&&<button className="text-button" onClick={()=>void openHelp()}>联系客服</button>}<button aria-label="关闭提示" onClick={()=>setError('')}><X size={15}/></button></div>}
   {uncertain&&<div className="warning-banner"><Clock3 size={16}/><span>确认结果尚未核实，请读取原状态，不要再次创建申请。</span><button onClick={()=>void refresh().catch(fail)}>读取状态</button></div>}
   {helpBlocked&&!paused&&<div className="warning-banner"><Pause size={16}/><span>本页已停止操作</span><button onClick={()=>void resume()}>继续服务</button></div>}{paused?<div className="paused-bar"><Pause size={20}/><div><strong>AI 已暂停自动处理</strong><p>需要继续时，点击继续 AI。</p></div><button className="primary-button" disabled={mutation} onClick={()=>void resume()}>继续 AI</button></div>:<><div className="composer-context"><button disabled={!state||busy} onClick={()=>void openOrders()}><Package size={14}/>{state?.order?state.order.merchant_name+' · '+state.order.id:'选择订单，让回答更准确'}<ChevronDown size={13}/></button>{state?.task?.active&&<button className="cancel-current" onClick={()=>void mutate('/cancel',{}).catch(()=>{})}>结束当前事项</button>}</div><form className="composer" onSubmit={e=>{e.preventDefault();void send()}}><textarea ref={composer} aria-label="输入你的问题" value={input} maxLength={2000} onChange={e=>setInput(e.target.value)} disabled={!state||busy||blocked} placeholder={state?'说说你遇到的问题，例如：这笔订单还能申请退货吗？':'选择演示账号后开始对话'} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}}/><button type="submit" className="send-button" aria-label="发送消息" disabled={!state||busy||blocked||!input.trim()}>{busy?<LoaderCircle size={20} className="spin"/>:<ArrowUp size={22}/>}</button></form></>}
   <div className="composer-note"><ShieldCheck size={12}/>AI 回答以适用资料与业务记录为依据。申请受理 ≠ 退款到账。<span>Enter 发送 · Shift + Enter 换行</span></div></div></main>
   <aside className="context-panel"><section className="context-section"><div className="section-heading"><span>当前服务事项</span><span className="small-tag">单事项</span></div>{state?.order?<><OrderMini order={state.order}/><button className="switch-order" disabled={busy} onClick={()=>void openOrders()}>切换订单<ChevronRight size={15}/></button></>:<div className="empty-object"><div><Package size={28}/></div><h3>先找到对的订单</h3><p>选择订单后，我会使用对应<br/>商户的规则为你提供帮助。</p><button className="soft-button" disabled={!state} onClick={()=>void openOrders()}>选择我的订单<ArrowRight size={15}/></button></div>}</section>
   <section className="context-section"><div className="section-heading"><span>处理进度</span><span className={'status-dot '+(paused?'amber':'')}/></div><ol className="steps">{['确认订单与诉求','获取事实与适用依据','核对内容，由你确认','查看明确的处理结果'].map((s,i)=>{const step=!state?.order?0:state.task?.status==='completed'?4:state.preview&&!state.preview.invalidated?2:1;return <li key={s} className={i<step?'done':i===step?'current':''}><span>{i<step?<Check size={12}/>:i+1}</span><div>{s}{i===step&&<small>{paused?'已暂停':state?.task?states[state.task.status]||'处理中':'等待开始'}</small>}</div></li>})}</ol>{state?.task?.unhandled?.length?<p className="micro">尚未承接：{state.task.unhandled.map(g=>labels[g]||g).join('、')}</p>:null}</section>
   <section className="trust-note"><Leaf size={21}/><h3>放心，每一步你都知道</h3><p>我会先说明依据，再给出下一步。涉及申请时，未经你的有效确认，不会自动提交。</p><div><LockKeyhole size={13}/>仅访问本人获授权资料</div></section><div className="sidebar-foot"><span>✦　YxWoof · 让服务更有温度</span><small>合成基准日 2026-09-07 · 不发生真实退款</small></div></aside></div>
  {showOrders&&<Modal title="选择要处理的订单" onClose={()=>setShowOrders(false)}><p className="modal-description">只展示当前账号的订单。切换订单将使原预览失效。</p>{ordersLoading?<div className="modal-loading"><LoaderCircle className="spin"/>正在获取本人订单</div>:ordersError?<div className="modal-loading" role="alert">{ordersError}<button onClick={()=>void openOrders()}>重新加载订单</button></div>:orders.length===0?<div className="modal-loading"><Package/>当前没有可用订单<button onClick={()=>void openOrders()}>重新查询</button></div>:<div className="order-list">{orders.map(o=><button key={o.id} disabled={mutation} className={state?.order?.id===o.id?'selected':''} onClick={()=>void bind(o)}><OrderMini order={o}/><span className="select-circle">{state?.order?.id===o.id&&<Check size={14}/>}</span></button>)}</div>}</Modal>}
  {help&&<Modal title="联系客服" onClose={()=>setHelp(null)}><div className="help-intro"><Headphones size={26}/><div><h3>需要更多帮助？</h3><p>你可以通过以下方式联系我们。</p></div></div>{help.entry?.url&&/^https:\/\//.test(help.entry.url)&&<a className="primary-button" href={help.entry.url} target="_blank" rel="noreferrer" onClick={()=>state&&track(state.id,'help_entry_opened',{task_id:state.task?.id,action_result:'opened'})}>{help.entry.label||'打开现有入口'}<ArrowUpRight size={15}/></a>}{help.entry?.contact&&<div className="business-card support-contact"><span className="field-label">客服邮箱</span><strong>{help.entry.contact}</strong><button className="soft-button" onClick={()=>void navigator.clipboard.writeText(help.entry?.contact||'').then(()=>setError('联系方式已复制')).catch(()=>setError(SERVICE_MESSAGE))}>复制联系方式</button></div>}{help.summary&&<ServiceSummary text={help.summary}/>}<div className="modal-actions">{help.summary&&<button className="soft-button" onClick={()=>void navigator.clipboard.writeText(help.summary).then(()=>{if(state)track(state.id,'service_summary_copied',{task_id:state.task?.id,action_result:'copied'});setError('服务摘要已复制')}).catch(()=>setError(SERVICE_MESSAGE))}><Copy size={15}/>复制服务摘要</button>}<button className="primary-button" disabled={mutation||helpLoading} onClick={()=>void resume()}>继续服务</button></div></Modal>}
  {source&&<Modal title={source.title} onClose={()=>setSource(null)}><div className="source-meta"><span>{source.merchant}</span><code>{source.policy_version}</code><span>合成演示资料</span><span>资料版本入库：{source.updated_at?new Date(source.updated_at).toLocaleString('zh-CN'):'未提供'}</span></div><EvidenceContent text={source.content}/></Modal>}
  {feedback&&state&&<Modal title="这次服务对你有帮助吗？" onClose={()=>setFeedback(null)}><FeedbackForm onSave={async data=>{await api(root+'/feedback',{...data,task_id:feedback.task_id});setFeedback(null);setError('已收到你的反馈。反馈不会改变业务申请状态。')}}/></Modal>}
  {identity&&<Modal title="切换合成演示账号" onClose={()=>setIdentity(false)}><p className="modal-description">切换将建立新演示会话，不删除或撤销原申请。原账号可通过订单查询查看原申请。</p><div className="identity-options"><button onClick={()=>void login('lin')} disabled={busy||profilesLoading||!profiles.includes('lin')}><span className="profile-initial">林</span>小林<ArrowRight size={17}/></button><button onClick={()=>void login('chen')} disabled={busy||profilesLoading||!profiles.includes('chen')}><span className="profile-initial peach">陈</span>小陈<ArrowRight size={17}/></button></div></Modal>}
 </div>
}
