import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowRight,Check,ChevronRight,Clock3,FileText,LoaderCircle,Package,ShieldCheck,ThumbsDown,ThumbsUp,X} from 'lucide-react';
import {track,uuid} from './api';
import type {Message,Order,Preview} from './types';
export const money=(c:number)=>(c/100).toFixed(2);
export function Avatar({large=false}:{large?:boolean}){return <img className={large?'avatar avatar-large':'avatar'} src="/api/v1/branding/avatar" alt="YxWoof 狗狗客服"/>}
export function Seen({children,cid,message,event='answer_presented',extra={},taskStartedAt}:{children:ReactNode;cid:string;message:Message;event?:string;extra?:Record<string,unknown>;taskStartedAt?:string}){
 const ref=useRef<HTMLDivElement>(null),sent=useRef(false);
 useEffect(()=>{const report=()=>{if(sent.current||document.visibilityState!=='visible'||!ref.current)return;const r=ref.current.getBoundingClientRect();if(r.top<window.innerHeight&&r.bottom>0){sent.current=true;let timing:Record<string,unknown>={};if(event==='answer_presented'){try{const s=JSON.parse(sessionStorage.getItem('yx.timing.'+cid)||'null');if(s&&!s.done&&s.timeOrigin===performance.timeOrigin&&!s.existing.includes(message.id)){timing={interaction_id:s.iid,duration_ms:performance.now()-s.start};s.done=true;sessionStorage.setItem('yx.timing.'+cid,JSON.stringify(s))}}catch{}}if(event==='answer_presented'&&taskStartedAt){try{const clock=JSON.parse(sessionStorage.getItem('yx.clock')||'null');if(clock?.origin===performance.timeOrigin){const elapsed=performance.timeOrigin+performance.now()+clock.offset-Date.parse(taskStartedAt);if(elapsed>=0)timing={...timing,task_elapsed_ms:elapsed,clock_uncertainty_ms:clock.uncertainty}}}catch{}}track(cid,event,{task_id:message.task_id||undefined,message_id:message.id,...timing,...extra})}};
 const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))report()},{threshold:.35});
 if(ref.current)observer.observe(ref.current);document.addEventListener('visibilitychange',report);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',report)}},[cid,event,message.id,message.task_id]);
 return <div ref={ref}>{children}</div>
}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const prior=document.activeElement as HTMLElement|null;ref.current?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const list=Array.from(ref.current?.querySelectorAll<HTMLElement>('button,input,textarea,a[href],select,[tabindex]:not([tabindex="-1"])')||[]).filter(x=>!x.hasAttribute('disabled')),first=list[0],last=list[list.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);prior?.focus()}},[]);
 return <div className="modal-scrim" onClick={onClose}><div className="modal" ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="关闭"><X size={20}/></button></div>{children}</div></div>
}
export function OrderMini({order:o}:{order:Order}){return <div className="order-mini"><div className="merchant-line"><span className="store-icon"><Package size={11}/></span>{o.merchant_name}<ChevronRight size={12}/><span className={'order-status '+(o.status==='delivered'?'delivered':'')}>{o.status==='delivered'?'已签收':'运输中'}</span></div><div className="product-row"><div className="product-art"><div className="storage-box"><span/><span/><span/></div></div><div><strong>{o.product}</strong><p>{o.spec}</p><span className="product-price">¥{money(o.price_cents)}<small>×1</small></span></div></div><div className="order-reference">{o.id}<span>{o.ordered_date}</span></div></div>}
export function ApplicationFields({initial,disabled,onSubmit,sources,onFieldCommit}:{initial:{reason?:string;condition?:string};disabled?:boolean;onSubmit:(data:{reason:string;condition:'unused_intact'})=>Promise<void>;sources?:ReactNode;onFieldCommit?:(field:string)=>void}){
 const committedReason=useRef(initial.reason||'');const [reason,setReason]=useState(initial.reason||''),[condition,setCondition]=useState(initial.condition==='unused_intact'),[error,setError]=useState('');
 return <form className="application-form" onSubmit={e=>{e.preventDefault();setError('');void onSubmit({reason,condition:'unused_intact'}).catch(e=>setError(e.message))}}><label>退货原因<textarea aria-label="退货原因" maxLength={300} minLength={2} required disabled={disabled} value={reason} onChange={e=>setReason(e.target.value)} onBlur={()=>{if(reason!==committedReason.current&&reason.trim()){committedReason.current=reason;onFieldCommit?.('reason')}}} placeholder="例如：尺寸不合适，商品尚未使用"/></label><label className="checkbox"><input type="checkbox" disabled={disabled} checked={condition} onChange={e=>{setCondition(e.target.checked);onFieldCommit?.('condition')}}/><span>我确认商品完好、未使用</span></label>{sources}{error&&<p className="field-error">{error}</p>}<button className="primary-button" disabled={disabled||!condition||reason.trim().length<2} type="submit">生成申请预览<ArrowRight size={15}/></button><p className="micro">生成预览不会提交申请，也不会执行退款。</p></form>
}
export function PreviewCard({preview:p,disabled,onConfirm,onCancel}:{preview:Preview;disabled?:boolean;onConfirm:()=>void;onCancel:()=>void}){
 const [time,setTime]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setTime(Date.now()),1000);return()=>clearInterval(t)},[]);
 const left=Math.max(0,Math.ceil((new Date(p.expires_at).getTime()-time)/1000)),valid=!p.invalidated&&left>0;
 return <div className={'business-card preview-card '+(!valid?'expired':'')}><div className="card-title"><FileText size={20}/><strong>退货申请预览</strong><span className="small-tag">{valid?'待你确认':'已失效'}</span></div><dl><dt>商户</dt><dd>{p.content.merchant}</dd><dt>订单明细</dt><dd>{p.content.order_id} · {p.content.spec}</dd><dt>申请类型</dt><dd>{p.content.type} ×{p.content.quantity}</dd><dt>退货原因</dt><dd>{p.content.reason}</dd><dt>商品状态</dt><dd>{p.content.condition}</dd><dt>原订单金额</dt><dd>¥{money(p.content.order_amount_cents)}<small>（非承诺退款金额）</small></dd></dl><p className="preview-notice"><ShieldCheck size={15}/>{p.content.notice}</p><div className="preview-time"><Clock3 size={13}/>{valid?'有效期剩余 '+Math.floor(left/60)+':'+String(left%60).padStart(2,'0'):'此预览不可再确认，请重新准备。'}</div><div className="card-buttons"><button className="primary-button" disabled={disabled||!valid} onClick={onConfirm}><Check size={15}/>确认提交申请</button><button className="soft-button" disabled={disabled||!valid} onClick={onCancel}>取消</button></div></div>
}
export function FeedbackForm({onSave}:{onSave:(data:Record<string,unknown>)=>Promise<void>}){
 const [helpful,setHelpful]=useState<boolean|null>(null),[comment,setComment]=useState(''),[csat,setCsat]=useState(''),[ces,setCes]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const id=useRef(uuid());
 return <form className="feedback-form" onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void onSave({id:id.current,helpful,category:helpful?'helpful':'not_resolved',comment,csat:csat?Number(csat):null,ces:ces?Number(ces):null}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}><div className="feedback-choices"><button type="button" aria-pressed={helpful===true} onClick={()=>setHelpful(true)}><ThumbsUp size={20}/>有帮助</button><button type="button" aria-pressed={helpful===false} onClick={()=>setHelpful(false)}><ThumbsDown size={20}/>还没解决</button></div><label>补充说明（可选）<textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={500} placeholder="告诉我们哪里可以做得更好"/></label><div className="rating-grid"><label>满意度（可选）<select value={csat} onChange={e=>setCsat(e.target.value)}><option value="">暂不评价</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} 分{n===5?' · 最满意':''}</option>)}</select></label><label>省力度（可选）<select value={ces} onChange={e=>setCes(e.target.value)}><option value="">暂不评价</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} 分{n===5?' · 最省力':''}</option>)}</select></label></div>{error&&<p role="alert" className="field-error">{error} 可保留内容后重试。</p>}<button className="primary-button" disabled={busy||helpful===null}>{busy&&<LoaderCircle size={15} className="spin"/>}提交反馈</button><p className="micro">自愿填写。反馈保存不代表业务问题已解决。</p></form>
}
